import "@/app/globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata = {
  title: "Admin | Rugby Klub 03 Berlin",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const messages = await getMessages();

  return (
    <html lang="de">
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
